# ~/.config/kitty/kitty.conf

## === FONTES ===
font_family FiraMono Nerd Font
bold_font FiraMono Nerd Font Bold
italic_font FiraMono Nerd Font Italic
bold_italic_font FiraMono Nerd Font Bold Italic
font_size 10.0

## === CORES ===
foreground              #abb2bf
background              #232326
selection_foreground    #232326
selection_background    #abb2bf

color0  #1e2127
color1  #e06c75
color2  #98c379
color3  #d19a66
color4  #61afef
color5  #c678dd
color6  #56b6c2
color7  #828791

color8  #5c6370
color9  #e06c75
color10 #98c379
color11 #d19a66
color12 #61afef
color13 #c678dd
color14 #56b6c2
color15 #828791

## === JANELA ===
background_opacity 0.9

## === SHELL ===
shell zsh

## === MAPAS DE TECLAS (opcional) ===
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

## === CONFIGURAÇAO ===
confirm_os_window_close 0
enable_audio_bell no

## === NEOVIM / IMAGE RENDERING ===
allow_remote_control yes
listen_on unix:/tmp/kitty
scrollback_lines 10000
